### PR TITLE
Add support for JP

### PR DESCRIPTION
**Pull request by pklreak**
Add support for JP

### CODE REVIEW

**Comment by rmondejar** [comment]
Hello @themisir, any chances for this PR to be reviewed?

**Comment by themisir** [comment]
Thanks for the contribution.

**Comment by rmondejar** [comment]
Thanks to you for this nice plugin 👍 

Do you know when we can expect a 1.0.2 version with JP included?

**Comment by themisir** [comment]
> Do you know when we can expect a 1.0.2 version with JP included?

Within a few hours hopefully

**Comment by rmondejar** [comment]
Awesome, thanks a lot!

**Pull request merged**
