### PR TITLE
added notBlank validator

### PR DESCRIPTION
**Pull request by masseelch**
I myself needed it and i think many other will do too. 

Tests are added.

### CODE REVIEW

**Comment by themisir** [comment]
I have changed `.required` logic yesterday which now checks if `length > 0`.  It's now available as prerelease that you can get [v0.1.6-next version here](https://pub.dev/packages/form_validator/versions/0.1.6-next).

**Comment by masseelch** [comment]
Ha. How unfortunate :smile: 

I still think, you should split `required` into `notNull` and `notBlank`.

**Comment by themisir** [comment]
> I still think, you should split `required` into `notNull` and `notBlank`.

I think value of `TextFormField` never equals to null.

**Comment by masseelch** [comment]
> I think value of `TextFormField` never equals to null.

If one would create a custom form field (like i did with a signature-field), it can return `null` as value. In that case the required validator would not work. It now checks for length, my custom type in a custom form field might not have a length property.

**Comment by themisir** [comment]
> > I think value of `TextFormField` never equals to null.
> 
> If one would create a custom form field (like i did with a signature-field), it can return `null` as value. In that case the required validator would not work. It now checks for length, my custom type in a custom form field might not have a length property.

😅 may you reopen the PR? I'll merge it after changing a bit.

**Comment by masseelch** [comment]
I somehow managed to delete my fork from my account :sweat_smile:.

I will fork again and create a new one. Still have a local copy.

**Comment by themisir** [comment]
Ok, don't worry I'll write myself. Btw thanks for PR. I will use `ValidationBuilder(optional: true | false)` parameter to validate not null and use `required` to validate `value.length > 0`.

**Comment by masseelch** [comment]
Hmm. I am not sure, if this is "clean".

**Comment by iksent** [comment]
Hello, @TheMisir!

When are you planning to release the new version?

"required"-validator does not work for TextEditingController, because it has an empty string as initial value, but "required"-validator checks for null.

UPD: But for now I use the extension and everything works. Thanks for the cool library!

```
extension CustomValidationBuilder on ValidationBuilder {
  ValidationBuilder notBlank() => add((value) {
    if (value == null || value.isEmpty) {
      return requiredMessage;
    }
    return null;
  });
}
```

**Pull request closed without merging**
