### PR TITLE
Added numeric validator

### PR DESCRIPTION
**Pull request by mohamed-yahyaoui**
I love this library.
I add numeric validator because I think it is needed.
I wish that this library will be adopted by the flutter team

### CODE REVIEW

**Comment by themisir** [comment]
Hey @mohamed-yahyaoui, can you briefly describe what exactly you are looking for in a separate issue please 😊

**Comment by mohamed-yahyaoui** [comment]
> Hey @mohamed-yahyaoui, can you briefly describe what exactly you are looking for in a separate issue please blush

About this pull request or about the proposal?

**Comment by themisir** [comment]
> I add numeric validator because I think it is needed.

Yeah, what exactly you mean with "numeric validator"?

**Comment by mohamed-yahyaoui** [comment]
> > Hey @mohamed-yahyaoui, can you briefly describe what exactly you are looking for in a separate issue please blush
> 
> About this pull request or about the proposal?

Ah sorry I mean a validator which ensures the value is a valid number

**Comment by themisir** [comment]
Hey sorry for my late reply, I have decided to not add any new validator. The primary reason for that decision is that I can't provide translations for all the currently supported languages for any new validation I might add. At this point without making any breaking change the best I can do is to support only the existing validators. However you can add custom validators using [this method](https://github.com/themisir/form-validator#extending-validationbuilder).

I am sorry for that decision but at this point it's outside of my capabilities to add a new validator with translations support.

**Pull request closed without merging**
